services:
       app:
              build: .
              container_name: esc-booking-backend
              ports:
                     - "3000:3000"
              env_file:
                     - .env
              networks:
                     - app-network
              restart: unless-stopped
              stdin_open: true
              tty: true

networks:
       app-network:
              driver: bridge
