services:
       app:
              build: .
              container_name: esc-booking-backend
              ports:
                     - "3000:3000"
              volumes:
                     - ./src:/usr/src/app/src
                     - ./tests:/usr/src/app/tests
                     - ./package.json:/usr/src/app/package.json
                     - ./tsconfig.json:/usr/src/app/tsconfig.json
                     - ./.env.dev:/usr/src/app/.env.dev
                     - /usr/src/app/node_modules
                     - ./jest.config.js:/usr/src/app/jest.config.js
              depends_on:
                     db-test:
                            condition: service_healthy
              networks:
                     - app-network
              restart: unless-stopped
              stdin_open: true
              tty: true

       db-test:
              image: mysql:8.0
              container_name: esc-mysql-test
              healthcheck:
                     test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "testuser", "-ptestpassword"]
                     interval: 5s
                     timeout: 5s
                     retries: 10
              environment:
                     MYSQL_ROOT_PASSWORD: rootpassword
                     MYSQL_DATABASE: esc_hotel_db
                     MYSQL_USER: testuser
                     MYSQL_PASSWORD: testpassword
              ports:
                     - "3307:3306"
              volumes:
                     - mysql_data:/var/lib/mysql
                     - ./init.sql:/docker-entrypoint-initdb.d/init.sql
              networks:
                     - app-network
              restart: unless-stopped

volumes:
       mysql_data:

networks:
       app-network:
              driver: bridge
